### ISSUE TITLE
Добавити статуси на відправлення/відправлено

### ISSUE THREAD

**Issue by BBKingH** [liubomyrgavryliv/gns-manufacturing#27]
Фінальна стадія продукту повинна працювати наступним чином:
Коли продукт в статусі "виготовлено" у менеджера з'являється можливість дати завдання для пакувальника "на відправку". Позиція отримує статус "на відправку" від менеджера - що бачить пакувальник та бере в роботу. По факту відправки пакувальник відзначає її як "виконано", статус замовлення стає - "відправлено". Після цього зі всіх інтерфейсів категорії "employee" це замовлення зникає.

**Comment by liubomyrgavryliv** [comment]
@BBKingH в бд з/явились нові таблиці - *wf_order_status_list* та *wf_order_status*, щоб трекати зміни статусу замовлення (в роботі, виготовлено, відправлено, скасовано). Додав відповідний фільтр у вікно фільтрів - можна фільтрувати за цими статусами. Додав можливість передавати замовлення на відправку, по факту просто додається нова стадія "відправка", яку виконує пакувальник, як зазвичай. Пофіксив історію замовлення, додав групування за стадіями, а також зміни статусів замовлення. Пофіксив скасування замовлення. Можеш пробувати тестити!

**Comment by BBKingH** [comment]
Працює, тільки слід внести деякі зміни. Пакувальник не має диференціяції між завданням на пакування та відправкою:
![image](https://user-images.githubusercontent.com/104343294/189686717-14a93fb8-487d-4d8e-9f40-da6f8fd14c46.png)
Можеш зробити так щоб у випадку якщо ставиться йому на відправку була піктограмка вантажівки як і в менеджера?
![image](https://user-images.githubusercontent.com/104343294/189687041-03adb7b6-242f-4ff0-b05a-b03ef04227fc.png)

**Comment by liubomyrgavryliv** [comment]
@BBKingH диференціацію ти описував в іншому feature request - [роботи за суміщенням](https://github.com/liubomyrgavryliv/gns-manufacturing/issues/28). Я не бачу смислу хардкодити диференціацію для одного тільки пакувальника, так як у вас багато хто крім нього буде задіяний на кілька стадіях одночасно, згідно того що ти описував. Тому, я зроблю кнопку-свіч замість попереднього діалогового вікна, і юзер, який задіяний на кількох етапах виробництва зможе переключатись між своїми задачами/станціями не покидаючи сторінку замовлень.

**Comment by BBKingH** [comment]
Добро, для інших це чудове рішення, може цього й насправді для пакувальника буде достатньо.
