### ISSUE TITLE
Інтерфейс відправки не працює

### ISSUE THREAD

**Issue by BBKingH** [liubomyrgavryliv/gns-manufacturing#33]
В пакувальника не працює перехід на інерфейс "відправка". При зміні повноважень виключно на delivery на інтерфейсі vasyljev-v отримую Server Error (500)
![image](https://user-images.githubusercontent.com/104343294/191907162-5f8c1505-7eba-46d7-9d7c-4d7c7fedcfb4.png)
Не можу знайти таблицю wf_final_product_log

**Comment by liubomyrgavryliv** [comment]
@BBKingH таблиці wf_final_product_log немає та і не було, для чого вона? помилка від того, що в wf_order_work_stage для замовлення 1155 два рази створена задача відправки - дублікат видалив, код поправив, щоб дублікат було неможливо створити.
