### ISSUE TITLE
Проблеми з відкликом на запити

### ISSUE THREAD

**Issue by BBKingH** [liubomyrgavryliv/gns-manufacturing#37]
Час від часу маємо довгий відклик на запит від сервера на різних інтерфейсах. Деколи як наслідок отримуємо:
![image](https://user-images.githubusercontent.com/104343294/192240752-cb45e46f-1562-45ec-9b03-e6bb4cfd57f1.png)
Через деякий час вертається в норму.

**Comment by liubomyrgavryliv** [comment]
@BBKingH таймаут воркерів збільшив до 120с. ти впевнений, що це моя проблема, а не вашої мережі? в логах не бачу нічого.

**Comment by BBKingH** [comment]
Ця проблема виникає і при підключенні через мобільну мережу і не має якогось чіткого систематичного характеру, принаймні по наших діях не спостерігається. Спочатку також думали що мережа, та інші сайти нормально грузяться. З'єднання стабільне. Я хіба що можу такі гальма фіксувати.

**Comment by liubomyrgavryliv** [comment]
@BBKingH зробив аналіз - кожні 40 хвилин на сервері бд запускався якийсь процес/тригер, який грузив проц на 100%, тому все падало. Це точно не з сайту, бо я тестив це ізолювавши всі з/єднання з бд. Зараз я додав трохи RAM до серверу бази даних і поміняв сервер взагалі. ціна трохи зросте, але схоже тепер загрузка проца на 100% пропала. принаймні останні 6 годин все норм. В мене є тільки одна здогадка чому це сталось - від міграції. Я не знаю як саме ця міграція відбувалась, і тому це єдине, за шо я не можу відповідати. Але все вказує на те шо ця проблема могла виникла після міграції. Хоча, це також не факт. Зараз треба спостерігати, і якщо це повториться, то пробувати хостити базу даних деінде.
