### ISSUE TITLE
Баг по долученню замовлень

### ISSUE THREAD

**Issue by BBKingH** [liubomyrgavryliv/gns-manufacturing#47]
Привіт бро!
З'явився один баг який проявляється на всіх наших компах та браузерах окрім Хрома на моєму компі. Працівники не можуть добавити замовлення, кнопка "Додати" не реагує. Проблема проявилась сьогодні. Налаштувань ніякий не змінювали, дизайн до речі також дещо змінився. Ось що тепер відображається у всіх працівників(поточна не робоча версія):
![image](https://user-images.githubusercontent.com/104343294/220622974-1e48a7c3-c616-452f-931f-3ada750c953b.png)
Ось що відображає мені в хромі і ще вчора відображалось у всіх інших(минула робоча версія):
![image](https://user-images.githubusercontent.com/104343294/220623298-58dcb9a0-0296-40d4-b6c8-f917e914cc01.png)
Як бачиш тепер зверху написи в працівників виділені синім фоном, та найважливіше що не можуть добавити нові замовлення.
Є якісь ідеї?

**Comment by liubomyrgavryliv** [comment]
Привіт! Швидше за все якийсь CSS файл не підтягує при загрузці сторінки, гляну на днях

**Comment by BBKingH** [comment]
Гаразд, дякую
