### ISSUE TITLE
Відображення в відправника

### ISSUE THREAD

**Issue by BBKingH** [liubomyrgavryliv/gns-manufacturing#49]
Привіт, по можливості прибери будь-ласка в пакування/відправка з відображення стовпці "Дата завершення" та "Телефон". Нажаль не влазить адекватно нам на екран планшета.
![image](https://user-images.githubusercontent.com/104343294/224564155-dbda052f-29c4-4f63-97f8-26446a9d967b.png)
Ну і я боюсь що такої дурні в фронтенді ще буде, можеш мені якось провести інструктаж по таким речам щоб тебе не відволікати зайвий раз по дурницям?

**Comment by liubomyrgavryliv** [comment]
@BBKingH все норм, кидай сюди, я буду міняти. Трохи переробив запити, зараз загалом сторінка менеджера має працювати швидше.
