### ISSUE TITLE
Опція подовжені ніжки/повернення на склад готової продукції

### ISSUE THREAD

**Issue by BBKingH** [liubomyrgavryliv/gns-manufacturing#55]
Йо! Брат, вже купу часу пройшло, все працює без лагів і всі задоволені, але треба дещо по функціоналу добавити.
Отже 1 і найважливіше - добав будь-ласка опцію "Ніжки" з варіантами "Подовжені"/"Стандартні" ось тут на стартовому екрані створення замовлень:
![image](https://github.com/liubomyrgavryliv/gns-manufacturing/assets/104343294/66f23e50-bdf0-45de-ad90-f3a5d0acd25d)
2. Потрібно щоб можна було повернути товар на склад готової продукції після відвантаження, це повернення тільки в превілейованих користувачів має бути доступне, до прикладу керівництва. Буває ситуація коли відправляємо топку, а клієнт вирішує іншу взяти і мусимо тоді на листочок занотовувати. Це не поспішає, але колупатись в базі даних для знаходження і видалення певного запису займає багато часу ну і ризики ще ті.

**Comment by liubomyrgavryliv** [comment]
@BBKingH додав новий статус "На складі" - ось PR[https://github.com/liubomyrgavryliv/gns-manufacturing/pull/56](https://github.com/liubomyrgavryliv/gns-manufacturing/pull/56). Тепер можна (1) повертати на склад відправлений продукт, (2) відправляти заново з складу, ну і (3) 1-2 може тривати безмежну кількість разів. Опція повернення доступна для користувачів з групи **lead**.  Також додав фільтр "На складі" в панель фільтрів.

Теоретично, повертати на склад можна будь-який відправлений продукт, ось як виглядають іконки повернення [https://zavod.gavrylivsons.ua/orders/?statuses=3](https://zavod.gavrylivsons.ua/orders/?statuses=3). Можливо треба обмежити можливість повернення не більше ніж тиждень-два після відправки?

Не знаю як до цього працювала функція створення багатьох однакових замовлень з одночасною передачою у виробництво, але локально в мене воно падало, тому пофіксив.

Думаю проблем з новим сетапом не має бути, але всяке може бути, тому пиши якщо що.

Я б подивився чому повільно грузиться головна сторінка, у вас уже багато замовлень, можна нормально відтестити.

**Comment by BBKingH** [comment]
Тут братчику все зйбс, ти класно зробив, цього повернення реально не вистачало. Щодо обмежень по терміну - не треба їх встановлювати. Приклад з життя: відправили топки до дилера, топки постояли в салоні, а потім в салон в'їбенив снаряд, салон згорів, топки які вдалось врятувати вернулись до нас на склад на відновлення. Ситуація унікальна, але принаймі можна якусь історію писати і опрацьовувати.
Щодо складу, то щось не те відображає, ти фільтрував HAVING MAX(order_status_id) = 2 ?

**Comment by liubomyrgavryliv** [comment]
@BBKingH йо! HAVING MAX(order_status_id) неправильно, бо в нас замовлення може йти на склад, потім назад на відправку, потім теоретично знов на склад. Тому я фільтрую просто за останнім записом в wf_order_status. Наприклад оце [замовлення 3138](https://zavod.gavrylivsons.ua/orders/3138/) - я бачу ви додали його на склад, потім знову передали у відправку. Але фільтр "На складі" буде його показувати, бо це останній статус замолення
